# SPDX-FileCopyrightText:  Open Energy Transition gGmbH
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: ji-gis
channels:
- conda-forge
- bioconda
- anaconda
dependencies:
- python>=3.8
- pip

- pypsa>=0.24, <0.25
- snakemake-minimal<8
- numpy
- pandas
- ipykernel
- jupyterlab
- pycountry
- sqlalchemy
- geoalchemy2
- geopandas
- xarray>=2023.11.0, <2023.12.0
- xlsxwriter
- psycopg2

- pip:
  - python-dotenv
  - openpyxl
