# SPDX-FileCopyrightText:  Open Energy Transition gGmbH
#
# SPDX-License-Identifier: AGPL-3.0-or-later

validation:
  countries: ["AU", "BR", "CO", "DE", "IN", "IT", "MX", "NG", "US", "ZA"]
  planning_horizon: [2021]

database_fill:
  countries: ["AU", "BR", "CO", "DE", "IN", "IT", "MX", "NG", "US", "ZA"]
  planning_horizon: [2021, 2050]
  version: "1" # version of writing to database