# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText:  Open Energy Transition gGmbH
#
# SPDX-License-Identifier: AGPL-3.0-or-later

import os
import sys
import pypsa
import pandas as pd
import geopandas as gpd
import pycountry
import logging
import warnings
warnings.filterwarnings("ignore")
from _helpers import mock_snakemake, update_config_from_wildcards, create_folder, \
                     load_network, get_base_network_path, get_solved_network_path, \
                     get_country_name, get_country_list, \
                     DATA_DIR, PYPSA_RESULTS_DIR, PYPSA_NETWORKS_DIR, RESULTS_DIR

logger = logging.getLogger(__name__)


def get_total_demand(n):
    """ Input:
            n - network
        Output:
            demand - total electricity demand in TWh
    """
    demand = n.loads_t.p_set.multiply(n.snapshot_weightings.objective, axis=0).sum().sum() / 1e6
    return demand.round(4)


def get_installed_capacities(n):
    """ Input:
            n - network
        Output:
            capacities - total electricity generation capacities in GW
    """
    # generator capacities
    gen_capacities = n.generators.groupby("carrier").p_nom.sum()
    # storage unit capacities
    storage_capacities = n.storage_units.groupby("carrier").p_nom.sum()
    # total capacities
    capacities = (pd.concat([gen_capacities, storage_capacities], axis=0) / 1e3).round(4)
    # drop load shedding
    if "load" in n.generators.carrier.unique():
        capacities.drop("load", inplace=True)
    return capacities


def get_generation_mix(n):
    """ Input:
            n - network
        Output:
            generation_mix - amount of consumed electricity generated by different carrier in TWh
    """
    # electricity generation by generators
    gen_generation = n.generators_t.p.multiply(n.snapshot_weightings.objective, axis=0).groupby(n.generators.carrier, axis=1).sum().sum()
    # electricity generation by storage unit
    storage_generation = n.storage_units_t.p.multiply(n.snapshot_weightings.objective, axis=0).groupby(n.storage_units.carrier, axis=1).sum().sum()
    # total generation mix
    generation_mix = pd.concat([gen_generation, storage_generation], axis=0) / 1e6
    return generation_mix.round(4)


def get_historic_demand(country_code, horizon):
    """ Input:
            country_code - two letter code of the country
        Output:
            demand - electricity demand in TWh from EIA (https://www.eia.gov/international/data/world/electricity/electricity-consumption)
    """
    # load EIA data
    eia_data = pd.read_csv(DATA_DIR+"EIA_demands.csv")
    eia_data.rename(columns={"Unnamed: 1":"country"}, inplace=True)
    eia_data["country"] = eia_data["country"].str.strip()
    eia_data.dropna(subset=['API'], inplace=True)
    eia_data["code_3"] = eia_data["API"].apply(lambda x: x.split('-')[2] if isinstance(x, str) and len(x.split('-'))>3 else x)
    
    # get the name of the country and three letter code
    country_name, country_code3 = get_country_name(country_code)
    
    # select the demand for given country and year in TWh (select based on 3 letter code first, then country name)
    if country_code3 and country_code3 in eia_data.code_3.unique():
        demand = float(eia_data.query("code_3 == @country_code3")[str(horizon)].values[0])
    elif country_name and country_name in eia_data.country.unique():
        demand = float(eia_data.query("country == @country_name")[str(horizon)].values[0])
    else:
        demand = None
    return demand


def get_historic_capacities(country_code, horizon):
    """ Input:
            country_code - two letter code of the country
        Output:
            capacity - generation capacities in MW from EIA (https://www.eia.gov/international/data/world/electricity/electricity-capacity)
    """
    # load EIA data
    eia_data = pd.read_csv(DATA_DIR+"EIA_installed_capacities.csv")
    eia_data.rename(columns={"Unnamed: 1":"country"}, inplace=True)
    eia_data["country"] = eia_data["country"].str.strip()
    eia_data["code_3"] = eia_data.dropna(subset=["API"])["API"].apply(lambda x: x.split('-')[2] if isinstance(x, str) and len(x.split('-'))>3 else x)

    # get the name of the country and three letter code
    country_name, country_code3 = get_country_name(country_code)

    # find capacities for given country
    if country_code3 and country_code3 in eia_data.code_3.unique():
        capacities = eia_data.query("code_3 == @country_code3")[["country", str(horizon)]]
    elif country_name and country_name in eia_data.country.unique():
        country_index = eia_data.query("country == @country_name").index[0]
        capacities = eia_data.iloc[country_index+1:country_index+14][["country", str(horizon)]]
    else:
        capacities = None
    return capacities


def get_historic_generation(country_code, horizon):
    """ Input:
            country_code - two letter code of the country
        Output:
            generation  - generation capacities in TWh from EIA (https://www.eia.gov/international/data/world/electricity/electricity-generation)
    """
    # load EIA data
    eia_data = pd.read_csv(DATA_DIR+"EIA_electricity_generation.csv")
    eia_data.rename(columns={"Unnamed: 1":"country"}, inplace=True)
    eia_data["country"] = eia_data["country"].str.strip()
    eia_data["code_3"] = eia_data.dropna(subset=["API"])["API"].apply(lambda x: x.split('-')[2] if isinstance(x, str) and len(x.split('-'))>3 else x)
    
    # get the name of the country and three letter code
    country_name, country_code3 = get_country_name(country_code)
    
    # find generation values for given country
    if country_code3 and country_code3 in eia_data.code_3.unique():
        generation = eia_data.query("code_3 == @country_code3")[["country", str(horizon)]]
    elif country_name and country_name in eia_data.country.unique():
        country_index = eia_data.query("country == @country_name").index[0]
        generation = eia_data.iloc[country_index+1:country_index+18][["country", str(horizon)]]
    else:
        generation = None
    return generation


def get_network_length(n_base):
    """ Input:
            n_base - base network of the country
        Output:
            length - total network length in km
            voltage_ratings - voltage ratings in kV
    """
    length = n_base.lines.length.sum().astype(int)
    voltage_ratings = n_base.lines.v_nom.astype(int).sort_values().unique()
    return length, voltage_ratings
    

def real_network_length(country_code):
    """ Input:
            country_code - two letter code of the country
        Output:
            length - total network length in km
            voltage_ratings - voltage ratings in kV
    """
    line_length = {"AU":56192, "BR":179297, "CN":1604838, "CO":29169, 
                   "DE":35796, "IN":706348, "IT":75246, "MX":109747, 
                   "NG":25633, "US":682812, "ZA": 0} # Eg: https://www.power-technology.com/data-insights/top-five-transmission-line-projects-in-colombia/
    voltage_ratings = {"AU": [66, 132, 275, 330], "BR": [138, 230, 345, 440, 500, 600, 750, 800], # https://ri.taesa.com.br/en/taesa/transmission-sector/ 
                       "CN": [110, 220, 330, 500, 750, 800, 1000], "CO": [110, 115, 220, 230, 500], # https://www.cigre.org/userfiles/files/Community/National%20Power%20System/2020_National_power_system_COLOMBIA%20-%202020_National_power_system_COLOMBIA.pdf
                       "DE": [110, 220, 380], "IN": [66, 132, 220, 400, 765], 
                       "IT": [132, 150, 220, 380], "MX": [115, 230, 400], "NG": [132, 330],
                       "US": [69, 115, 138, 230, 345, 500, 765], "ZA": [66, 88, 132, 220, 330]}
    return line_length[country_code], voltage_ratings[country_code]

    
def compare_capacities(network_capacities, historic_capacities):
    """ Input:
            network_capacities - capacities obtained from the network in GW
            historic_capacities - capacities obtained from EIA in GW
        Output:
            capacities - DataFrame comparing two data
    """
    # bring historic data into format
    historic_capacities["country"] = historic_capacities.country.str.replace("(million kW)","").str.strip()
    historic_capacities.set_index("country", inplace=True)
    historic_capacities.columns = ["EIA Data"]
    historic_capacities.rename(index={"Capacity":"Total capacity", 
                                      "Hydroelectricity":"Hydro", 
                                      "Biomass and waste":"Biomass", 
                                      "Hydroelectric pumped storage":"PHS"}, inplace=True)
    historic_capacities.drop(index=["Renewables", "Non-hydroelectric renewables", 
                                    "Solar, tide, wave, fuel cell", "Tide and wave"], inplace=True)
    historic_capacities = historic_capacities.loc[["Nuclear", "Fossil fuels", "Hydro", "PHS", "Solar", "Wind", "Biomass", "Geothermal", "Total capacity"], :]
    
    # bring capacities from the network into format
    all_carriers = ["nuclear", "coal", "lignite", "CCGT", "OCGT", "hydro", "ror", "PHS", "solar", "offwind-ac", "offwind-dc", "onwind", "biomass", "geothermal"]
    network_capacities = network_capacities.reindex(all_carriers, fill_value=0)
    network_capacities.rename(index={"nuclear":"Nuclear", "solar":"Solar", "biomass":"Biomass", "geothermal":"Geothermal"}, inplace=True)
    network_capacities["Fossil fuels"] = network_capacities[["coal", "lignite", "CCGT", "OCGT"]].sum()
    network_capacities["Hydro"] = network_capacities[["hydro", "ror"]].sum()
    network_capacities["Wind"] = network_capacities[["offwind-ac", "offwind-dc", "onwind"]].sum()
    network_capacities = network_capacities.loc[["Nuclear", "Fossil fuels", "Hydro", "PHS", "Solar", "Wind", "Biomass", "Geothermal"]]
    network_capacities["Total capacity"] = network_capacities.sum()
    network_capacities.name = "PyPSA Model"
    network_capacities = network_capacities.to_frame()

    # merge two data
    capacities = pd.concat([network_capacities, historic_capacities], axis=1).astype(float)
    capacities["Error (%)"] = (100*(capacities["PyPSA Model"] - capacities["EIA Data"])/capacities["EIA Data"]).astype(float).round(2)
    capacities.fillna(0, inplace=True)
    capacities.index.name = "Capacities [GW]"
    return capacities.round(2)


def compare_demands(network_demand, historic_demand):
    """ Input:
            network_demand - demand obtained from the network in TWh
            historic_demand - demand obtained from EIA in TWh
        Output:
            demand - DataFrame comparing two data
    """
    demand = pd.DataFrame(columns=["PyPSA Model", "EIA Data"])
    demand.loc["Electricity Demand [TWh]", ["PyPSA Model", "EIA Data"]] = [network_demand, historic_demand]
    demand["Error (%)"] = (100*(demand["PyPSA Model"] - demand["EIA Data"])/demand["EIA Data"]).astype(float)
    return demand.round(2)


def compare_generation(network_generation, historic_generation):
    """ Input:
            network_generation - electricity generation obtained from the network in TWh
            historic_generation - electricity generation obtained from EIA in TWh
        Output:
            generation - DataFrame comparing two data
    """
    # bring historic data into format
    historic_generation["country"] = historic_generation.country.str.replace("(billion kWh)","").str.strip()
    historic_generation.set_index("country", inplace=True)
    historic_generation.columns = ["EIA Data"]
    historic_generation = historic_generation.astype(float)
    historic_generation.rename(index={"Generation":"Total generation", 
                                      "Hydroelectricity":"Hydro", 
                                      "Biomass and waste":"Biomass", 
                                      "Hydroelectric pumped storage":"PHS"}, inplace=True)
    historic_generation.drop(index=["Fossil fuels", "Renewables", "Non-hydroelectric renewables", 
                                    "Solar, tide, wave, fuel cell", "Tide and wave"], inplace=True)
    historic_generation.loc["Load shedding"] = None
    historic_generation.loc["Natural gas"] = historic_generation.loc[["Natural gas", "Other gases"]].sum()
    historic_generation = historic_generation.loc[["Nuclear", "Coal", "Natural gas", "Oil", "Hydro", "PHS", "Solar", "Wind", "Biomass", "Geothermal", "Load shedding", "Total generation"], :]
    
    # bring generation from the network into format
    all_carriers = ["nuclear", "coal", "lignite", "CCGT", "OCGT", "oil", "hydro", "ror", "PHS", "solar", "offwind-ac", "offwind-dc", "onwind", "biomass", "geothermal", "load"]
    network_generation = network_generation.reindex(all_carriers, fill_value=0)
    network_generation.rename(index={"nuclear":"Nuclear", "oil":"Oil", "solar":"Solar", "biomass":"Biomass", "geothermal":"Geothermal", "load":"Load shedding"}, inplace=True)
    network_generation["Coal"] = network_generation[["coal", "lignite"]].sum()
    network_generation["Natural gas"] = network_generation[["CCGT", "OCGT"]].sum()
    network_generation["Hydro"] = network_generation[["hydro", "ror"]].sum()
    network_generation["Wind"] = network_generation[["offwind-ac", "offwind-dc", "onwind"]].sum()
    network_generation["Load shedding"] /= 1e3
    network_generation = network_generation.loc[["Nuclear", "Coal", "Natural gas", "Oil", "Hydro", "PHS", "Solar", "Wind", "Biomass", "Geothermal", "Load shedding"]]
    network_generation["Total generation"] = network_generation.sum()
    network_generation.name = "PyPSA Model"
    network_generation = network_generation.to_frame()

    # merge two data
    generation = pd.concat([network_generation, historic_generation], axis=1).astype(float)
    generation["Error (%)"] = (100*(generation["PyPSA Model"] - generation["EIA Data"])/generation["EIA Data"]).astype(float).round(2)
    generation.fillna(0, inplace=True)
    generation = generation.loc[["Nuclear", "Coal", "Natural gas", "Oil", "Hydro", "PHS", "Solar", "Wind", "Biomass", "Geothermal", "Load shedding", "Total generation"], :].round(2)
    return generation


def compare_network_lines(network_length, network_voltages, real_length, real_voltages):
    """ Input:
            network_length - network length in km
            network_voltages - network voltages in kV
            real_length - real network length in km
            real_voltages - real network voltages in kV
        Output:
            df_network - DataFrame comparing two data
    """
    voltage_ratings = sorted(list(set(network_voltages) | set(real_voltages)))
    df_network = pd.DataFrame(index=["Line length [km]"]+voltage_ratings)
    df_network.loc["Line length [km]", ["PyPSA Model", "Cited Sources"]] = [network_length, real_length]
    df_network.loc["Line length [km]", "Error (%)"] = (100*(network_length - real_length)/real_length).astype(float).round(2)
    df_network.loc[network_voltages, "PyPSA Model"] = "+"
    df_network.loc[real_voltages, "Cited Sources"] = "+"
    return df_network


if __name__ == "__main__":
    if "snakemake" not in globals():
        snakemake = mock_snakemake(
            "validate", 
            countries="US",
            planning_horizon="2021",
        )
    # update config based on wildcards
    config = update_config_from_wildcards(snakemake.config, snakemake.wildcards)


    # create results folder
    create_folder(RESULTS_DIR)

    # country code 
    country_code = config["validation"]["countries"]

    # validation horizon
    horizon = config["validation"]["planning_horizon"]

    # perform valdiation
    with pd.ExcelWriter(snakemake.output.table, engine='xlsxwriter') as writer:
        # get filepath of the network
        filepath = get_solved_network_path(country_code, horizon, PYPSA_RESULTS_DIR)
        # get filepath to base network
        base_filepath = get_base_network_path(country_code, horizon, PYPSA_NETWORKS_DIR)
        
        # load the network
        n = load_network(filepath)
        # load base network
        n_base = load_network(base_filepath)

        # get total electricity demand
        demand = get_total_demand(n)

        # get optimal generation capacities
        generation_capacities = get_installed_capacities(n)

        # get generation mix
        generation_mix = get_generation_mix(n)

        # get network length and voltage ratings
        network_length, network_voltages = get_network_length(n_base)

        # get historic electricity consumption of the country
        historic_demand = get_historic_demand(country_code, horizon)

        # get historic generation capacities of the country
        historic_capacities = get_historic_capacities(country_code, horizon)

        # get historic generation mix of the country
        historic_generation = get_historic_generation(country_code, horizon)

        # get real network length and voltages
        real_length, real_voltages = real_network_length(country_code)

        # compare the data
        demand_comparison = compare_demands(demand, historic_demand)
        capacity_comparison = compare_capacities(generation_capacities, historic_capacities)
        generation_comparison = compare_generation(generation_mix, historic_generation)
        network_comparison = compare_network_lines(network_length, network_voltages, real_length, real_voltages)

        demand_comparison.to_excel(writer, sheet_name=country_code, startrow=0, startcol=0)
        capacity_comparison.to_excel(writer, sheet_name=country_code, startrow=3, startcol=0)
        generation_comparison.to_excel(writer, sheet_name=country_code, startrow=0, startcol=5)
        network_comparison.to_excel(writer, sheet_name=country_code, startrow=0, startcol=10)
